project:
  type: website
  output-dir: docs
  
website:
  page-footer: Copyright 2024 | <a href="https://marce10.github.io">Marcelo Araya-Salas</a>
  title: "Reproducible Science Workshop, REU OTS 2024"
  search: true
  site-url: https://marce10.github.io/OTS_REU_OS_2024/
  repo-url: https://github.com/maRce10/OTS_REU_OS_2024/
  navbar:
    right:
      - icon: github
        href: https://github.com/maRce10/OTS_REU_OS_2024/
        aria-label: GitHub
    left:
      - href: index.qmd
        text: Home
      # - text: "Program"
      #   href: program.qmd
      - text: "Tutorials"
        menu:
        - text: "R basics"
          href: r_basics.qmd
        - text: "Coding and reproducibility"
          href: coding_and_reproducibility.qmd
        - text: "Reearch compendiums"
          href: research_compendiums.qmd
        - text: "Intro to git/github"
          href: intro_to_git_and_github.qmd
      - text: "Course prep"
        href: course_prep.qmd
      - text: "Code sharing"
        href: https://codefile.io/f/inMsojTFoN
      - text: "Instructor"
        href: instructor.qmd

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    
editor: visual
