---
toc: true
toc-depth: 3
toc-location: left
number-sections: true
highlight-style: pygments
format:
  html:
    df-print: kable
    code-fold: show
    css: styles.css
    link-external-icon: true
    link-external-newwindow: true    
---

::: {.alert .alert-success}
### Before the course starts {.unnumbered .unlisted}

- Make sure you install all the software we will be using [as detailed in here](course_prep.qmd)
- Read/watch the additional materials for day 1

:::

 

## Day 1

---

### **Refresh basic R concepts** <a href="r_basics.qmd" class="btn btn-warning btn-xs" role="button">Tutorial</a>

-   Object types in R
-   Subsetting
-   Style matters
-   R documentation

### **Coding and reproducible research** <a href="coding_and_reproducibility.qmd" class="btn btn-warning btn-xs" role="button">Tutorial</a>

-   Free software and code
-   Why R?
-   Tools for reproducible programming

::: {.alert .alert-warning}
### Additional materials

#### Readings

-   Baker, M. (2016). [Reproducibility crisis](https://www.nature.com/articles/533452a). nature, 533(26), 353-66.

#### Videos

-   [Reproducibility crisis](https://www.youtube.com/watch?v=FpCrY7x5nEE&t=54s)
-   [Reproducibility and open science](https://www.youtube.com/watch?v=c-bemNZ-IqA&t=384s)

#### Optional 

-   Alston, J. M., & Rick, J. A. (2021). [A beginner's guide to conducting reproducible research](http://jessicarick.com/s/Alston_ReproducibleResearch_BulletinESA_Rev1.pdf). Bulletin of the Ecological Society of America, 102(2), 1-14.
-   Culina, A., van den Berg, I., Evans, S., & Sánchez-Tójar, A. (2020). [Low availability of code in ecology: A call for urgent action](https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.3000763). PLoS Biology, 18(7), e3000763.

:::

 


::: {.alert .alert-info}
### Practice

1. On a scientific journal of your preference pick up 10 open access papers (or just 10 papers if you have access) 

1. Skim each paper to check if they have attempted to make it reproducible and which research components have been shared (like data or code). If there are not open research papers in the 10 you pick up keep looking until you find one.  

1. Try to access the supplementary materials containing the shared materials

:::

------------------------------------------------------------------------

 

## Day 2 

---

### **Research compendiums** <a href="research_compendiums.qmd" class="btn btn-warning btn-xs" role="button">Tutorial</a>

-   Folder structure formats
-   R packages as templates for compendiums
-   R Packages for Compendium Generation

### **Intro to git/gihub** <a href="intro_to_git_and_github.qmd" class="btn btn-warning btn-xs" role="button">Tutorial</a>

-  Git for version control
-  Setting up a git project
-  Version control and collaboration with github


::: {.alert .alert-warning}
### Additional materials

#### Readings

- Vuorre, M., & Curley, J. P. (2018). [Curating research assets: A tutorial on the Git version control system](https://journals.sagepub.com/doi/full/10.1177/2515245918754826). Advances in Methods and Practices in Psychological Science, 1(2), 219-236.

#### Videos

- [What is git?](https://www.youtube.com/watch?v=2ReR1YJrNOM)

- [What is version control?](https://www.youtube.com/watch?v=Yc8sCSeMhi4)

- [Git vs github](https://www.youtube.com/watch?v=xJXgvr8bPes)

#### Optional 

-   Bryan, J. (2018). [Excuse me, do you have a moment to talk about version control?](https://peerj.com/preprints/3159.pdf). The American Statistician, 72(1), 20-27.

:::

